[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[ports]]
name = "http"
port = 9001
protocol = "http"

[[ports]]
name = "websocket"
port = 9002
protocol = "tcp"
